import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5174/');
  await page.getByRole('button', { name: 'EXPLORE MENU' }).click();
  await page.getByRole('button', { name: 'Add to Cart' }).first().click();
  await page.getByRole('button', { name: 'Add to Cart' }).nth(1).click();
  await page.getByRole('button', { name: 'Add to Cart' }).nth(2).click();
  await page.getByRole('button', { name: 'Add to Cart' }).nth(4).click();
  await page.getByRole('button', { name: 'Add to Cart' }).nth(3).click();
  await page.getByRole('button', { name: 'Add to Cart' }).nth(5).click();
  await page.locator('div:nth-child(10) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(11) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(12) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(16) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(15) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(14) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(13) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(17) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(18) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(19) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(20) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(24) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(23) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(22) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(21) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(25) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(26) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(27) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(27) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(32) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(31) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(30) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(29) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(34) > .p-5 > .w-full').click();
  await page.locator('div:nth-child(35) > .p-5 > .w-full').click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Proceed to Checkout' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).click();
  await page.getByRole('textbox', { name: 'Full Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('M');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('Michelle ');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('Michelle D');
  await page.getByRole('textbox', { name: 'Full Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Full Name *' }).fill('Michelle Daluz');
  await page.getByRole('textbox', { name: 'Contact Number *' }).click();
  await page.getByRole('textbox', { name: 'Contact Number *' }).fill('09758583764');
  await page.getByRole('textbox', { name: 'Alternative Contact Number (' }).click();
  await page.getByRole('textbox', { name: 'Alternative Contact Number (' }).fill('');
  await page.getByRole('textbox', { name: 'Alternative Contact Number (' }).click();
  await page.getByRole('textbox', { name: 'Alternative Contact Number (' }).fill('09268804514');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).click();
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).fill('M');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).fill('Mitch ');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).fill('Mitch D');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).fill('Mitch De ');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).fill('Mitch De G');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Facebook Name (Optional)' }).fill('Mitch De Guzman');
  await page.getByRole('textbox', { name: 'Email Address (Optional)' }).click();
  await page.getByRole('textbox', { name: 'Email Address (Optional)' }).fill('michelleddaluz@gmail.com');
  await page.locator('div').filter({ hasText: /^₱15300\.00$/ }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '↓ Download E-Receipt File' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: '🏠 Back to Home' }).click();
});