import { test, expect } from '@playwright/test';

test('It should pass the full E2E POS Flow', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('textbox', { name: '@gmail.com' }).click();
  await page.getByRole('textbox', { name: '@gmail.com' }).fill('admin@cakelytics.com');
  await page.getByRole('textbox', { name: '••••••••' }).click();
  await page.getByRole('textbox', { name: '••••••••' }).fill('password123');
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('link', { name: 'Point Of Sale' }).click();
  await page.getByRole('button', { name: 'Package' }).click();
  await page.getByRole('button', { name: 'Pastry' }).click();
  await page.getByRole('button', { name: 'Celebration Material' }).click();
  await page.getByPlaceholder('Search product...').click();
  await page.getByRole('button', { name: 'All' }).click();
  await page.locator('label').click();
  await page.getByPlaceholder('Search product...').fill('ch');
  await page.getByRole('button', { name: 'ADD' }).first().click();
  await page.getByRole('button', { name: 'Complete Order' }).click();
  await page.getByPlaceholder('Enter cash amount').click();
  await page.getByPlaceholder('Enter cash amount').fill('700');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Finalize Transaction' }).click();
  await page.getByRole('button', { name: 'Pre-Order' }).click();
  await page.getByRole('button', { name: 'Package' }).click();
  await page.getByRole('button', { name: 'All', exact: true }).click();
  await page.getByRole('button', { name: 'Package' }).click();
  await page.getByRole('button', { name: 'Pastry' }).click();
  await page.getByRole('button', { name: 'All', exact: true }).click();
  await page.getByRole('button', { name: 'ADD' }).first().click();
  await page.getByRole('textbox', { name: 'Phone Number *' }).click();
  await page.getByRole('textbox', { name: 'Phone Number *' }).fill('09268804514');
  await page.getByRole('textbox', { name: 'Customer Name *' }).click();
  await page.getByRole('textbox', { name: 'Customer Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Customer Name *' }).fill('H');
  await page.getByRole('textbox', { name: 'Customer Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Customer Name *' }).fill('Hazel');
  await page.locator('input[type="date"]').fill('2026-07-30');
  await page.locator('input[type="time"]').fill('00:00');
  await page.getByRole('button', { name: 'Confirm Pre-Order' }).click();
  await page.getByPlaceholder('Enter cash amount').click();
  await page.getByPlaceholder('Enter cash amount').fill('700');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Finalize Transaction' }).click();
  await page.getByRole('link', { name: 'All Orders' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Cancel Order' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Cancel Order' }).click();
  await page.getByRole('button', { name: 'View Details' }).nth(2).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Mark as Ready' }).click();
  await page.getByRole('link', { name: 'Product Management' }).click();
  await page.getByRole('link', { name: 'All Orders' }).click();
  await page.getByRole('button', { name: 'Confirmed' }).click();
  await page.getByRole('button', { name: 'Ready' }).click();
  await page.getByRole('button', { name: 'Completed' }).click();
  await page.getByRole('button', { name: 'Cancelled' }).click();
  await page.getByRole('button', { name: 'Completed' }).click();
  await page.getByRole('button', { name: 'Cancelled' }).click();
  await page.getByRole('link', { name: 'Product Management' }).click();
  await page.getByRole('link', { name: 'Point Of Sale' }).click();
  await page.getByRole('link', { name: 'Product Management' }).click();
  await page.getByRole('button', { name: 'Edit' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Product Name' }).click();
  await page.getByRole('textbox', { name: 'Product Name' }).fill('Keyki');
  await page.getByRole('textbox', { name: 'Product Name' }).press('Enter');
  await page.getByRole('button', { name: 'Submit' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Delete' }).nth(4).click();
  await page.getByRole('button', { name: '+ Add Product' }).click();
  await page.getByRole('textbox', { name: 'Product Name' }).click();
  await page.getByRole('textbox', { name: 'Product Name' }).fill('keyk');
  await page.getByPlaceholder('0', { exact: true }).click();
  await page.getByPlaceholder('0', { exact: true }).fill('1000');
  await page.getByRole('textbox', { name: 'e.g. Themed Cake (7x5) w/' }).click();
  await page.getByRole('textbox', { name: 'e.g. Themed Cake (7x5) w/' }).fill('round cake');
  await page.getByText('Upload Image').click();
  await page.getByLabel('Upload Image').setInputFiles('tests/fixtures/sample1.jpg');
  await page.getByText('Upload Image').click();
  await page.getByLabel('Upload Image').setInputFiles('tests/fixtures/sample2.jpg');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Edit' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Product Name' }).click();
  await page.getByRole('textbox', { name: 'Product Name' }).fill('keyki');
  await page.getByRole('button', { name: 'Submit' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Delete' }).nth(4).click();
});